FROM ubuntu:20.04

ARG CORTEZA_PATH=https://releases.cortezaproject.org/files/corteza-2021.6.0-rc.3-linux-amd64.tar.gz


RUN apt-get update && apt-get install rpm -y

RUN mkdir -p ~/rpmbuild/SOURCES ~/rpmbuild/SPECS


