name: release

on:
  push:
    tags:
      - '**'


jobs:

  release-any:
    runs-on: ubuntu-latest
    env:
      ENDPOINT: https://releases.cortezaproject.org/files
      RELEASE_SFTP_KEY: ${{ secrets.RELEASE_SFTP_KEY }}
      RELEASE_SFTP_URI: ${{ secrets.RELEASE_SFTP_URI }}
    steps:
      - run: echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - run: |
          curl --silent --location "${{ env.ENDPOINT }}/corteza-server-${{ env.BUILD_VERSION }}-linux-amd64.tar.gz" | \
            tar -xzmok -C .
          mv corteza-server dist
          rm -rf dist/webapp
      - run: |
          mkdir dist/webapp
          curl --silent --location "${{ env.ENDPOINT }}/corteza-webapp-${{ env.BUILD_VERSION }}.tar.gz" | \
            tar -xzmok -C dist/webapp
      - run: tar -C dist -czf corteza-${{ env.BUILD_VERSION }}-linux-amd64.tar.gz $(dir dist)
      - run: echo ${{ env.RELEASE_SFTP_KEY }} | base64 -d > .upload-rsa
      - run: chmod 0400 .upload-rsa
      - run: |
          echo "put corteza-${{ env.BUILD_VERSION }}-linux-amd64.tar.gz" | \
            sftp -q -o "StrictHostKeyChecking no" -i .upload-rsa ${{ env.RELEASE_SFTP_URI }}
      - run: rm -f .upload-rsa

  release-docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        if: ${{ !env.ACT }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build \
            --build-arg VERSION="${{ env.BUILD_VERSION }}" \
            -t cortezaproject/corteza:${{ env.BUILD_VERSION }} .
        if: ${{ !env.ACT }}
      - run: docker push cortezaproject/corteza:${{ env.BUILD_VERSION }}
        if: ${{ !env.ACT }}

  release-rpm:
    runs-on: ubuntu-latest
    needs: [ release-any ]
    env:
      ENDPOINT: https://releases.cortezaproject.org/files
      RELEASE_SFTP_KEY: ${{ secrets.RELEASE_SFTP_KEY }}
      RELEASE_SFTP_URI: ${{ secrets.RELEASE_SFTP_URI }}
    steps:
      - run: echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        if: ${{ !env.ACT }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: ./build.sh
        working-directory: rpm
      - run: echo ${{ env.RELEASE_SFTP_KEY }} | base64 -d > .upload-rsa
      - run: chmod 0400 .upload-rsa
      - run: |
          echo "put rpm/RPMS/x86_64/corteza*.rpm" | \
            sftp -q -o "StrictHostKeyChecking no" -i .upload-rsa ${{ env.RELEASE_SFTP_URI }}
      - run: rm -f .upload-rsa
